name: Package Bearsampp Pricing Tables Module

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build-package:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Get current date
        id: date
        run: echo "VERSION=$(date +'%Y.%-m.%-d')" >> $GITHUB_ENV
      
      - name: Create package directory
        run: mkdir -p package/mod_bearsampp_pricing_tables
      
      - name: Copy module files
        run: |
          cp mod_bearsampp_pricing_tables.php package/mod_bearsampp_pricing_tables/
          cp mod_bearsampp_pricing_tables.xml package/mod_bearsampp_pricing_tables/
          cp helper.php package/mod_bearsampp_pricing_tables/
          cp License.txt package/mod_bearsampp_pricing_tables/
          cp index.html package/mod_bearsampp_pricing_tables/
          cp -r css package/mod_bearsampp_pricing_tables/
          cp -r elements package/mod_bearsampp_pricing_tables/
          cp -r tmpl package/mod_bearsampp_pricing_tables/
          cp -r language package/mod_bearsampp_pricing_tables/
      
      - name: Update version in XML file
        run: |
          sed -i "s/<version>.*<\/version>/<version>${{ env.VERSION }}<\/version>/" package/mod_bearsampp_pricing_tables/mod_bearsampp_pricing_tables.xml
          sed -i "s/<creationDate>.*<\/creationDate>/<creationDate>$(date +'%B %Y')<\/creationDate>/" package/mod_bearsampp_pricing_tables/mod_bearsampp_pricing_tables.xml
      
      - name: Generate directory tree
        run: |
          apt-get update && apt-get install -y tree
          tree package/mod_bearsampp_pricing_tables > package/directory-structure.txt
      
      - name: Create ZIP archive
        run: |
          cd package
          zip -r mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip mod_bearsampp_pricing_tables
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Bearsampp Pricing Tables v${{ env.VERSION }}
          files: |
            package/mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip
            package/directory-structure.txt
          draft: false
          prerelease: false
          body: |
            Bearsampp Pricing Tables Module v${{ env.VERSION }}
            
            ### Download Options:
            - Download directly from this release page
            - Access the artifact from the Actions tab of this workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload artifact for easy access from GitHub Actions
      # Upload artifact for easy access from GitHub Actions
      - name: Upload to GitHub Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod_bearsampp_pricing_tables_${{ env.VERSION }}
          path: package/mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip
          retention-days: 90
          if-no-files-found: error
      
      # Add information about downloading the artifact
      - name: Artifact Download Information
        run: |
          echo "::notice::The module package has been uploaded as an artifact."
          echo "::notice::You can download it from the Actions tab of this workflow run."
          echo "::notice::Go to Actions → This workflow → This run → Artifacts section → Download 'mod_bearsampp_pricing_tables_${{ env.VERSION }}'"
