name: Package Bearsampp Pricing Tables Module

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build-package:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant permission to write to repository
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          token: ${{ secrets.GITHUB_TOKEN }}  # Needed for pushing changes
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Get current date
        id: date
        run: |
          echo "BASE_VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "CREATION_DATE=$(date +'%Y %B %d')" >> $GITHUB_ENV
          echo "CURRENT_YEAR=$(date +'%Y')" >> $GITHUB_ENV
      
      - name: Check for existing tags and resolve version conflicts
        run: |
          # Get all existing tags
          git fetch --tags
          
          # Check if the base version tag already exists
          BASE_TAG="${{ env.BASE_VERSION }}"
          if git rev-parse "$BASE_TAG" >/dev/null 2>&1; then
            echo "Tag $BASE_TAG already exists, finding next available version..."
            
            # Find all tags that match the pattern {BASE_VERSION}.{n}
            MATCHING_TAGS=$(git tag -l "$BASE_TAG.*")
            
            if [ -z "$MATCHING_TAGS" ]; then
              # No sub-versions exist, use .1
              NEXT_VERSION="${{ env.BASE_VERSION }}.1"
            else
              # Find the highest sub-version
              HIGHEST_SUBVERSION=$(echo "$MATCHING_TAGS" | sed "s/^$BASE_TAG\.//" | sort -n | tail -1)
              NEXT_SUBVERSION=$((HIGHEST_SUBVERSION + 1))
              NEXT_VERSION="${{ env.BASE_VERSION }}.$NEXT_SUBVERSION"
            fi
            
            echo "VERSION=$NEXT_VERSION" >> $GITHUB_ENV
            echo "Using version: $NEXT_VERSION"
          else
            echo "VERSION=${{ env.BASE_VERSION }}" >> $GITHUB_ENV
            echo "Using base version: ${{ env.BASE_VERSION }}"
          fi
      
      - name: Create package directory
        run: mkdir -p package/mod_bearsampp_pricing_tables
      
      - name: Copy module files
        run: |
          cp mod_bearsampp_pricing_tables.php package/mod_bearsampp_pricing_tables/
          cp mod_bearsampp_pricing_tables.xml package/mod_bearsampp_pricing_tables/
          cp helper.php package/mod_bearsampp_pricing_tables/
          cp License.txt package/mod_bearsampp_pricing_tables/
          cp index.html package/mod_bearsampp_pricing_tables/
          cp -r css package/mod_bearsampp_pricing_tables/
          cp -r elements package/mod_bearsampp_pricing_tables/
          cp -r tmpl package/mod_bearsampp_pricing_tables/
          cp -r language package/mod_bearsampp_pricing_tables/
      
      - name: Update XML file in repository
        run: |
          XML_FILE="mod_bearsampp_pricing_tables.xml"
          if [ -f "$XML_FILE" ]; then
            # Make a backup of the original file
            cp "$XML_FILE" "${XML_FILE}.bak"
            
            # Display original content
            echo "Original XML content:"
            cat "$XML_FILE" | grep -E "<version>|<creationDate>|<copyright>"
            
            # Update version using perl for more reliable regex handling
            perl -i -pe 's|(<version>).*?(</version>)|$1${{ env.VERSION }}$2|g' "$XML_FILE"
            
            # Update creationDate
            perl -i -pe 's|(<creationDate>).*?(</creationDate>)|$1${{ env.CREATION_DATE }}$2|g' "$XML_FILE"
            
            # Update copyright year
            perl -i -pe 's|(<copyright>Copyright \(C\))[0-9]{4}( Bearsampp</copyright>)|$1${{ env.CURRENT_YEAR }}$2|g' "$XML_FILE"
            
            echo "Updated XML file in repository"
            echo "Updated XML content:"
            cat "$XML_FILE" | grep -E "<version>|<creationDate>|<copyright>"
            
            # Show diff of changes
            echo "Changes made to XML file:"
            diff "${XML_FILE}.bak" "$XML_FILE" || true
          else
            echo "::warning::XML file not found in repository, skipping update"
          fi
      
      - name: Commit changes to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes to commit
          if git diff --exit-code; then
            echo "No changes to commit"
          else
            git add "mod_bearsampp_pricing_tables.xml"
            git commit -m "Update version to ${{ env.VERSION }}, creation date to ${{ env.CREATION_DATE }}, and copyright year to ${{ env.CURRENT_YEAR }}"
            git push origin main
            echo "Changes committed and pushed to repository"
          fi
      
      - name: Generate directory tree
        run: |
          apt-get update && apt-get install -y tree
          tree package/mod_bearsampp_pricing_tables > package/directory-structure.txt
      
      - name: Create ZIP archive
        run: |
          cd package
          zip -r mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip mod_bearsampp_pricing_tables
          echo "Created ZIP archive: mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip"
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Bearsampp Pricing Tables ${{ env.VERSION }}
          files: |
            package/mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip
            package/directory-structure.txt
          draft: false
          prerelease: false
          body: |
            Bearsampp Pricing Tables Module ${{ env.VERSION }}
            
            ### Download Options:
            - Download directly from this release page
            - Access the artifact from the Actions tab of this workflow run
            
            ### Changes:
            - Updated version to ${{ env.VERSION }}
            - Updated creation date to ${{ env.CREATION_DATE }}
            - Updated copyright year to ${{ env.CURRENT_YEAR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload artifact for easy access from GitHub Actions
      # Upload artifact for easy access from GitHub Actions
      - name: Upload to GitHub Artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: mod_bearsampp_pricing_tables_${{ env.VERSION }}
          path: package/mod_bearsampp_pricing_tables_${{ env.VERSION }}.zip
          retention-days: 90
          if-no-files-found: error
      
      # Add information about downloading the artifact
      - name: Artifact Download Information
        run: |
          echo "::notice::The module package has been uploaded as an artifact."
          echo "::notice::You can download it from the Actions tab of this workflow run."
          echo "::notice::Go to Actions → This workflow → This run → Artifacts section → Download 'mod_bearsampp_pricing_tables_${{ env.VERSION }}'"
